version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/cloud.lazycat.app.owncast.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: owncast

build:
  toolchains: []
  run_buildscript: false

images:
  - id: owncast
    target: service
    service: owncast
    source: docker.io/owncast/owncast
    channel: stable
    sort: semver
    tag_regex: '^\d+\.\d+\.\d+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    continue_if_newer_version: true
    skip_if_version_exists: true
    retry:
      enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: OwnCast
    summary: Published from GitHub Actions
